# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases: {list-collab: api repos/$1/$2/collaborators, remove-collab: api -X DELETE repos/$1/$2/collaborators/$3, uni: '!cp ~/.config/gh/hosts.yml.uni ~/.config/gh/hosts.yml && gh auth status', personal: '!cp ~/.config/gh/hosts.yml.personal ~/.config/gh/hosts.yml && gh auth status', repo-content: api repos/$1/$2/contents/$3, list-inv: api repos/$1/$2/invitations, delete-inv: api -X DELETE repos/$1/$2/invitations/$3, add-collab: api -X PUT repos/$1/$2/collaborators/$3 -f permission=$4}
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
